// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwynSG3kdlYDEDus_sSPldhoReKO3CCsk',
    appId: '1:960783908208:android:be294f4cb9fc86712c23b5',
    messagingSenderId: '960783908208',
    projectId: 'corpool-1d9c0',
    storageBucket: 'corpool-1d9c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCanfhbvlnJpUcc-bBd7uEhicebvey-GAU',
    appId: '1:960783908208:ios:2606ee72f8991c1f2c23b5',
    messagingSenderId: '960783908208',
    projectId: 'corpool-1d9c0',
    storageBucket: 'corpool-1d9c0.appspot.com',
    androidClientId: '960783908208-hnnskknpqqtglq96sbhsh5a2sa5c7j4m.apps.googleusercontent.com',
    iosClientId: '960783908208-90sjth66dmnbvdl3chcf9v0q0s5mtjgr.apps.googleusercontent.com',
    iosBundleId: 'com.noobs.corpoolFlutter',
  );
}
